name: Build and deploy Java project to Azure Function App - chaboxx-function

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: chaboxx-function
  PACKAGE_DIRECTORY: '.'
  JAVA_VERSION: '21'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java SDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Build with Maven'
        run: |
          cd '${{ env.PACKAGE_DIRECTORY }}'
          mvn clean package

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6EAF84390913455ABF6D29B0B8591025 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B7DDB2B75F7A405BA3ADB0C99261B599 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_59E08157EAE54F8B8E9CCA4CBE821E71 }}

      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.PACKAGE_DIRECTORY }}
          respect-pom-xml: true
